#!/bin/bash

# Dependencies: imagemagick, BMHand font

TOP="the joke"
BOTTOM="you"
OUTPUT="meme"

SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPTPATH="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SCRIPTPATH/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

SCRIPTPATH="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

while getopts "ht:b:o:" opt 
do
    case "$opt" in
    h|\?)
        echo "Usage: $0 [-t top ] [-b bottom] [-o output]"
        echo "       $0 [top [bottom [output]]]"
        exit 0
        ;;
    t)
        TOP=$OPTARG
        ;;
    b)
        BOTTOM=$OPTARG
        ;;
    o)
        OUTPUT=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

TOP=${1:-$TOP}
BOTTOM=${2:-$BOTTOM}
OUTPUT=${3:-$OUTPUT}

OUTPUT="${OUTPUT%.*}.png"

FONTSIZE=40

[[ $( echo $BOTTOM | wc -c ) -gt 8 ]] && FONTSIZE=27

BOTTOM="$( echo $BOTTOM | fold -w 11 -s )"

IMAGE="$SCRIPTPATH/youthejoke.png"

convert $IMAGE \
    -font "$SCRIPTPATH/BamsHand.ttf" -pointsize 40 -fill black \
    -gravity Center -annotate '0,0,0,-130' "$TOP" \
    -pointsize $FONTSIZE \
    -gravity SouthWest -annotate +310+20 "$BOTTOM" \
    $OUTPUT
